### ISSUE TITLE
SCP Changes prevent the TSE-SE template from Launching

### ISSUE THREAD

**Issue by joshuahigginson1** [aws-samples/landing-zone-accelerator-on-aws-for-tse-se#1]
The removal of the `arn:${PARTITION}:iam::*:role/cdk-accel-*` role from SCPs pertaining to IAM and Lambda prevent the solution from launching, due to errors in the Logging stages.

**Comment by oliviergaumond** [comment]
The change in SCP in combination with the change to specify a `customDeploymentRole` in the global-config.yaml should work together.
https://github.com/aws-samples/landing-zone-accelerator-on-aws-for-tse-se/blob/3e33ce49a59f433e2fb6b6361ff28ae13f443713/config/global-config.yaml#L26

If that is not the case for you, could you post more detailed error messages.

**Comment by joshuahigginson1** [comment]
Amazing, that's the missing piece of the puzzle we needed. Thank you Olivier :)
