### ISSUE TITLE
Unable to view Cloudtrail events in Global Region

### ISSUE THREAD

**Issue by richardkeit** [aws-samples/landing-zone-accelerator-on-aws-for-tse-se#10]
IAM actions and other global services log records in `us-east-1` of Cloudtrail, because of `GLB1` of [4.8.2. Sensitive policy](https://github.com/aws-samples/landing-zone-accelerator-on-aws-for-tse-se/tree/main/architecture-doc#482-sensitive-policy) users are unable to diagnose issues within IAM.

https://github.com/aws-samples/landing-zone-accelerator-on-aws-for-tse-se/blob/bd511d46aee84dbffd33c9052e5800223bc43419/config/service-control-policies/LZA-Guardrails-Sensitive.json#L216-L288

This affects usability and end users are presented with the below when viewing `Cloudtrail` within `us-east-1`:
~~~
User: arn:aws:sts::XXX:assumed-role/AWSReservedSSO_AWSAdministratorAccess_2903639fd9b44a7f/richard.keit.lza.2.sso is not authorized to perform: cloudtrail:LookupEvents with an explicit deny in a service control policy

~~~

**Comment by rjjaegeraws** [comment]
Hi Richard,

Thank you for creating this issue. I will bring this to the team, and we will review.

**Comment by rjjaegeraws** [comment]
This made it into the v1.11.0-a release. Thanks!
