### ISSUE TITLE
Dead Link in Architecture Overview

### ISSUE THREAD

**Issue by ptcrash** [aws-samples/landing-zone-accelerator-on-aws-for-tse-se#2]
At the end of file `architecture-doc/readme.md`, the link in the text reading `Continue to LZA configuration files and installation instructions` sends you to a file that doesn't exist in the repo. It doesn't look like there's a general readme.md in the config directory, so it's a little hard to know what the next step is after reading through the overview doc.

**Comment by rjjaegeraws** [comment]
Thanks for reporting.

It should link to the install instructions here: https://github.com/aws-samples/landing-zone-accelerator-on-aws-for-tse-se/blob/main/install.md

We will correct this in our next release.

**Comment by rjjaegeraws** [comment]
Fixed in 1.7.0-a release.
