### ISSUE TITLE
TSE-SE SCPs Configuration breaks Pipeline at Prepare Stage LZA v1.6.3

### ISSUE THREAD

**Issue by de-cx-cloud** [aws-samples/landing-zone-accelerator-on-aws-for-tse-se#3]
**Describe the bug**
After upgrade the LZA to v1.6.3 the SCPs Configuration from AWS TSE-SE Architecture breaks the AWSAccelerator Pipeline at Prepare Stage

**To Reproduce**
Run Pipeline after upgrade

**Expected behavior**
Apply SCPs with the AWSAcceleratorPipeline Role

**Please complete the following information about the solution:**

- [ ] Version: v1.6.3

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [X] Region: eu-central-1
- [X] Was the solution modified from the version published on this repository? NO
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [X] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [X] Were there any errors in the CloudWatch Logs?

**Screenshots**
![Screenshot 2024-05-15 at 18 22 55](https://github.com/aws-samples/landing-zone-accelerator-on-aws-for-tse-se/assets/160848020/f9a7bfe3-435b-4d84-96d9-5b63e4e76477)

**Additional context**
The error message indicates that the user arn:aws:sts::XXXXXX:assumed-role/AWSControlTowerExecution/acceleratorBootstrapCheck does not have permission to perform the ssm:GetParameter action on the resource arn:aws:ssm:eu-central-1:XXXXX:parameter/accelerator/logging/central-bucket/kms/arn.

**Comment by rjjaegeraws** [comment]
Thanks for reporting. This has been detected once, and has not been reproducible in test environments. The LZA development team has written a code change to catch this case that will be in the next published LZA release (expected in a few weeks). 
The advice from that team is to unsure that the default 'Full AWS Access' SCP is properly configured on the Organizational Units holding the accounts where this is happening.

**Comment by de-cx-cloud** [comment]
hello @rjjaegeraws,
Thank you for your response. The issue arose due to the following sequence of actions:

1. Upgraded LZA to version 1.6.3 as the TSE-SE SCPs were not properly applied in version 1.6.2.
2. The SCPs in LZA 1.6.2 were deployed at the Account stage within the us-east-1 global region but were not visible in the SCPs list.
3. Upon the initial execution, all SCPs were successfully implemented.
4. The problem surfaced after integrating new organizational units into AWSAccelerator-Guardrails-Sensitive-Part-1, WSAccelerator-Guardrails-Part-1, and AWSAccelerator-Guardrails-Part-0 configurations.
5. Subsequently, upon launching AWSAcceleratorPipeline, the following error was encountered:
   `
   Error: User: arn:aws:sts::ACCOUNT_NUM:assumed-role/AWSControlTowerExecution/acceleratorBootstrapCheck is not authorized to perform ssm:GetParameter on resource arn:aws:ssm:eu-central-1:ACCOUNT_NUM:parameter/accelerator/logging/central-bucket/kms/arn because no service control policy allows the ssm:GetParameter action
   `

Further investigation revealed that during the **Account Stage**, LZA attempted to delete all SCPs, failing to remove specific SCPs already applied to certain Organizational Units, causing Control Tower Drift Configuration and disrupting the AWSAccelerator Pipeline. Thanks

**Comment by rjjaegeraws** [comment]
Thanks for this. I will send this to the LZA dev team to see if this reveals a case they haven't accounted for in the fix.

**Comment by mlewis7127** [comment]
I have run into the exact same problem rolling out a new LZA landing zone with the TSE config with version 1.6.3. This is failing in the Accounts stage of the pipeline. I am using Organizations and not ControlTower, so the error message is below:

```
$ /codebuild/output/src3423/src/s3/00/source/packages/@aws-accelerator/accelerator/node_modules/.bin/ts-node --transpile-only cdk.ts synth --stage accounts --require-approval never --config-dir /codebuild/output/src3423/src/s3/01 --partition aws
2024-05-21 15:41:57.532 | error | accelerator | {"name":"AccessDeniedException","$fault":"client","$metadata":{"httpStatusCode":400,"requestId":"231bd904-9847-4346-8e37-164149d5921a","attempts":1,"totalRetryDelay":0},"__type":"AccessDeniedException","message":"User: arn:aws:sts::891377294609:assumed-role/OrganizationAccountAccessRole/acceleratorBootstrapCheck is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:eu-west-2:891377294609:parameter/accelerator/logging/central-bucket/kms/arn because no service control policy allows the ssm:GetParameter action"}
2024-05-21 15:41:57.535 | error | app | User: arn:aws:sts::891377294609:assumed-role/OrganizationAccountAccessRole/acceleratorBootstrapCheck is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:eu-west-2:891377294609:parameter/accelerator/logging/central-bucket/kms/arn because no service control policy allows the ssm:GetParameter action
2024-05-21 15:41:57.535 | error | toolkit | Error: User: arn:aws:sts::891377294609:assumed-role/OrganizationAccountAccessRole/acceleratorBootstrapCheck is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:eu-west-2:891377294609:parameter/accelerator/logging/central-bucket/kms/arn because no service control policy allows the ssm:GetParameter action
2024-05-21 15:41:57.615 | error | accelerator | Runtime Error
/codebuild/output/src3423/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/accelerator.ts:58
    throw new Error('Synthesis failed');
    ^
``` 

I had also added a new OU that was targetted by the SCPs:
* AWSAccelerator-Guardrails-Part-0
* AWSAccelerator-Guardrails-Part-1

**Comment by de-cx-cloud** [comment]
Dear @mlewis7127,

The issue was caused by a problem with the Landing Zone Accelerator (LZA). Upgrading LZA **to v1.6.4** should resolve it.
See the release notes: [LZA v1.6.4](https://github.com/awslabs/landing-zone-accelerator-on-aws/releases/tag/v1.6.4)
