### ISSUE TITLE
Dead link in post-deployment.md

### ISSUE THREAD

**Issue by 0arko** [aws-samples/landing-zone-accelerator-on-aws-for-tse-se#5]
Hi, there seems to be a dead link in the landing-zone-accelerator-on-aws-for-tse-se/post-deployment.md doc under 'Architecture Overview' relating to the ALB Forwarding Architecture. This is an interesting mechanism so would be good to see what the link should be

Thanks

**Comment by rjjaegeraws** [comment]
Thanks for reporting this. The image can be found in our mirrored repo [here](https://github.com/aws-samples/landing-zone-accelerator-on-aws-for-cccs-medium/blob/main/architecture-doc/images/alb-forwarding-architecture.png), but I will have this corrected in our next release.
