### ISSUE TITLE
After update, daily Network Firewall costs spiked

### ISSUE THREAD

**Issue by ka-rostom** [aws-samples/landing-zone-accelerator-on-aws-for-tse-se#8]
Upgraded from 1.9.2-b to 1.10.0-a, and saw a significant jump in Network Firewall spend (~$19.00/daily).

Looking through the diffs between the two releases, I am having a hard time figuring out which changes in the latest LZA release `1.10.0-a` would cause this jump in Network Firewall spend.

We upgraded our LZA setup on November 13th, which correlates directly with the jump in Network Firewall spend in the attached graph (attached below).

![image](https://github.com/user-attachments/assets/12514063-e699-43d6-a898-c0e481fed5a8)

Please advise. Thank you! :)

**Comment by oliviergaumond** [comment]
@ka-rostom were you using AWS Network Firewall before?  The [pricing for Network Firewall Endpoint](https://aws.amazon.com/network-firewall/pricing/) is 0.395$/h which roughly adds up to 19$/day when deploying firewall endpoints in two Availability Zones such as in this sample configuration. It looks like those endpoints were initially deployed on Nov 13th based on your graph.

**Comment by ka-rostom** [comment]
Were those added to the latest version? 

We upgraded our LZA setup on November 13th, which correlates directly with the jump in Network Firewall spend in the attached graph (attached below).

**Comment by rjjaegeraws** [comment]
Hi ka-rostom,

Here's a screenshot showing 3 months of Network Firewall in a test environment which would have different versions applied. Your increase spend aligns with the default deployment as Olivier mentioned above. 
![image](https://github.com/user-attachments/assets/a3e54c6c-6e41-4cfd-90ed-f635668a124b)

I recommend that you compare your Network-Config.yaml with your previous versions and look closely at the Network Firewall section. Was it previously deployed?

**Comment by ka-rostom** [comment]
Thanks for the kind replies and attention. Let me check again - I guess I may have missed something.

Will report back :)
